name: Build and Deploy Angular (luna-y-sol)

on:
  push:
    branches:
      - main  # Cambia a 'master' si tu rama principal se llama así

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js (asegúrate de usar una versión compatible, p.ej. 18)
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Instalar Angular CLI globalmente
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # 5. Compilar la aplicación Angular (con el baseHref adecuado)
      - name: Build Angular app
        run: ng build --configuration production --base-href /luna-y-sol/

      # 6. Desplegar en GitHub Pages (publicando el contenido de la carpeta 'docs')
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/browser
